<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.numworx.swingbrowser</groupId>
		<artifactId>swingbrowser-parent</artifactId>
		<version>0.0.6</version>
	</parent>
	<artifactId>swingbrowser-api</artifactId>
	<packaging>bundle</packaging>
	<name>Swingbrower API</name>
	<dependencies>
	  	<dependency>
  		<groupId>org.osgi</groupId>
  		<artifactId>org.osgi.core</artifactId>
  		<version>5.0.0</version>
  		<scope>provided</scope>
  		<optional>true</optional>
	  	</dependency>
	
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Export-Package>nl.numworx.swingbrowser.api,nl.numworx.swingbrowser.scorm</Export-Package>
					</instructions>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>