<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.numworx.swingbrowser</groupId>
    <artifactId>swingbrowser-parent</artifactId>
    <version>0.0.11</version>
  </parent>
  <artifactId>swingbrowser-ext</artifactId>
  <properties>
  	<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
	<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>  
  </properties>
  <dependencies>
  	<dependency>
  		<groupId>org.osgi</groupId>
  		<artifactId>org.osgi.core</artifactId>
  		<version>6.0.0</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>nl.numworx.swingbrowser</groupId>
  		<artifactId>swingbrowser-api</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>javax.servlet</groupId>
  		<artifactId>servlet-api</artifactId>
  		<version>2.4</version>
  	</dependency>
  	<dependency>
  		<groupId>org.osgi</groupId>
  		<artifactId>osgi.cmpn</artifactId>
  		<version>5.0.0</version>
  		<scope>provided</scope>
  	</dependency>

		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.connect</artifactId>
			<version>0.2.0</version>
			<scope>test</scope>
		</dependency>

  	<dependency>
  		<groupId>com.googlecode.json-simple</groupId>
  		<artifactId>json-simple</artifactId>
  		<version>1.1.1</version>
  	</dependency>
  	<dependency>
  		<groupId>nl.numworx</groupId>
  		<artifactId>org.eclipse.equinox.http</artifactId>
  		<version>1.0.500</version>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>fi.beans</groupId>
  		<artifactId>numworxlf</artifactId>
  		<version>2.4.2</version>
  	</dependency>
  </dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<_snapshot>${osgi.qualifier}</_snapshot>
						<Bundle-Activator>nl.numworx.swingbrowser.ext.Activator</Bundle-Activator>
						<Export-Package>!*</Export-Package>
						<Private-Package>nl.numworx.swingbrowser.ext</Private-Package>
						<Import-Package>nl.numworx.swingbrowser.api;version="[1.1,1.2)",*</Import-Package>
						<Provide-Capability>osgi.service;objectClass="nl.numworx.swingbrowser.api.SwingBrowserFactory";type="ext";uses:="nl.numworx.swingbrowser.api";effective:="active"</Provide-Capability>
					</instructions>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<packaging>bundle</packaging>
	<description>Externe browser implementatie</description>
	<name>Swingbrowser extern</name>
	<profiles>
		<profile>
			<id>felix</id>
			<dependencies>
<dependency>
    <groupId>org.apache.felix</groupId>
    <artifactId>org.apache.felix.httplite.complete</artifactId>
    <version>0.1.6</version>
    <scope>test</scope>
    <exclusions>
    	<exclusion>
    		<groupId>org.apache.felix</groupId>
    		<artifactId>org.apache.felix.httplite.core</artifactId>
    	</exclusion>
    	<exclusion>
    		<groupId>org.osgi</groupId>
    		<artifactId>org.osgi.compendium</artifactId>
    	</exclusion>
    </exclusions>
</dependency>
			</dependencies>
		
		</profile>
	</profiles>
</project>