<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.numworx.swingbrowser</groupId>
		<artifactId>swingbrowser-parent</artifactId>
		<version>0.0.3-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>swingbrowser-jfx</artifactId>
	<packaging>bundle</packaging>
	<name>Swingbrowser JFX</name>
	<dependencies>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.core</artifactId>
			<version>5.0.0</version>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>swingbrowser-api</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<_snapshot>${osgi.qualifier}</_snapshot>
						<Bundle-Activator>nl.numworx.swingbrowser.jfx.Activator</Bundle-Activator>
						<Export-Package>!nl.numworx.swingbrowser.jfx</Export-Package>
						<Private-Package>nl.numworx.swingbrowser.jfx</Private-Package>
						<Import-Package>nl.numworx.swingbrowser.api;provide:=true,*</Import-Package>
					</instructions>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>